// 从官方 Assets/Female3DCG/Female3DCG.js 提取的资产级 Effect 静态表（scripts/extract-effects.js 生成）。
// 键是 Group/Name（资产名不全局唯一，必须带组名）。只含四维感知关心的效果：
// 口塞/失明/失聪/移动限制/双手占用。
// ⚠️ 变体级 Effect（如绳子绑法自带的 Freeze）不在此表——它们经官方流程切变体后
// 会写进 wire 数据的 Property.Effect，运行时与下表合并（CharacterGetEffects 同款逻辑）。
export const ASSET_EFFECTS: Record<string, string[]> = {
  "ItemAddon/CeilingChain": ["Freeze"],
  "ItemAddon/CeilingNeckCuff": ["Freeze"],
  "ItemAddon/CeilingRope": ["Freeze"],
  "ItemArms/ArmbinderJacket": ["Block"],
  "ItemArms/ArmbinderSuit": ["Block"],
  "ItemArms/BedMetalCuffs": ["Block", "Freeze"],
  "ItemArms/BitchSuit": ["Block"],
  "ItemArms/Bolero": ["Block"],
  "ItemArms/BondageBouquet": ["Block"],
  "ItemArms/BondageBra": ["Block"],
  "ItemArms/BoxTieArmbinder": ["Block"],
  "ItemArms/CanvasStraitjacket1": ["Block"],
  "ItemArms/CeilingShackles": ["Block", "Freeze"],
  "ItemArms/Chains": ["Block"],
  "ItemArms/CollarCuffs": ["Block"],
  "ItemArms/CollarMetalcuffs": ["Block"],
  "ItemArms/DuctTape": ["Block"],
  "ItemArms/FourLimbsShackles": ["Block"],
  "ItemArms/FullBodyLeatherHarness": ["Block"],
  "ItemArms/FullBodyShackles": ["Block"],
  "ItemArms/FullLatexSuit": ["Block", "Freeze"],
  "ItemArms/FurStraitJacket": ["Block"],
  "ItemArms/FuturisticArmbinder": ["Block"],
  "ItemArms/FuturisticStraitjacket": ["Block"],
  "ItemArms/HeavyYoke": ["Block"],
  "ItemArms/HempRope": ["Block"],
  "ItemArms/HighSecurityStraitJacket": ["Block"],
  "ItemArms/InflatableDress": ["Block"],
  "ItemArms/InflatableStraightLeotard": ["Block"],
  "ItemArms/LatexArmbinder": ["Block"],
  "ItemArms/LatexBoxtieLeotard": ["Block"],
  "ItemArms/LatexButterflyLeotard": ["Block"],
  "ItemArms/LatexSleevelessLeotard": ["Block"],
  "ItemArms/LeatherArmbinder": ["Block"],
  "ItemArms/LeatherArmSplints": ["Block"],
  "ItemArms/LeatherStraitJacket": ["Block"],
  "ItemArms/Manacles": ["Block", "Freeze"],
  "ItemArms/MedicalBedRestraints": ["Block"],
  "ItemArms/MermaidSuit": ["Block", "Freeze"],
  "ItemArms/MetalCuffs": ["Block"],
  "ItemArms/NylonRope": ["Block"],
  "ItemArms/PantyhoseBody": ["Block"],
  "ItemArms/PantyhoseBodyOpen": ["Block"],
  "ItemArms/PawPaddedPetsuitArms": ["Block"],
  "ItemArms/PetCrawler": ["Block"],
  "ItemArms/Pillory": ["Block"],
  "ItemArms/PlasticWrap": ["Block"],
  "ItemArms/PrisonLockdownSuit": ["Block"],
  "ItemArms/PrisonSJ": ["Block"],
  "ItemArms/Ribbons": ["Block"],
  "ItemArms/SeamlessLatexArmbinder": ["Block"],
  "ItemArms/SeamlessStraitDress": ["Block"],
  "ItemArms/SeamlessStraitDressOpen": ["Block"],
  "ItemArms/ShinyArmbinder": ["Block"],
  "ItemArms/ShinyPetSuit": ["Block"],
  "ItemArms/ShinyStraitjacket": ["Block"],
  "ItemArms/SleepSac": ["Block"],
  "ItemArms/Slime": ["Block"],
  "ItemArms/SmoothLeatherArmbinder1": ["Block"],
  "ItemArms/StraitDress": ["Block"],
  "ItemArms/StraitDressOpen": ["Block"],
  "ItemArms/StraitJacket": ["Block"],
  "ItemArms/StraitLeotard": ["Block"],
  "ItemArms/StrappedPetsuitArms": ["Block"],
  "ItemArms/StrictLeatherPetCrawler": ["Block"],
  "ItemArms/SturdyLeatherBelts": ["Block"],
  "ItemArms/Tentacles": ["Block"],
  "ItemArms/ThinLeatherStraps": ["Block"],
  "ItemArms/TightJacket": ["Block"],
  "ItemArms/TightJacketCrotch": ["Block"],
  "ItemArms/TransportJacket": ["Block"],
  "ItemArms/UnderBedBondageCuffs": ["Block", "Freeze"],
  "ItemArms/Web": ["Block", "Freeze"],
  "ItemArms/WoodenCuffs": ["Block"],
  "ItemArms/WrappedBlanket": ["Block"],
  "ItemArms/WristShackles": ["Block"],
  "ItemArms/Yoke": ["Block"],
  "ItemArms/Zipties": ["Block"],
  "ItemBoots/LeatherToeCuffs": ["Freeze"],
  "ItemBoots/MonoHeel": ["Freeze"],
  "ItemBoots/Slime": ["Freeze"],
  "ItemBoots/ToeCuffs": ["Freeze"],
  "ItemBoots/ToeTie": ["Freeze"],
  "ItemBoots/Zipties": ["Freeze"],
  "ItemDevices/Bed": ["Mounted"],
  "ItemDevices/BondageBench": ["Mounted"],
  "ItemDevices/BrickWall": ["Freeze", "Tethered"],
  "ItemDevices/BurlapSack": ["Block", "Freeze"],
  "ItemDevices/Cage": ["Freeze"],
  "ItemDevices/ChangingTable": ["Freeze"],
  "ItemDevices/Crib": ["Freeze"],
  "ItemDevices/DisplayCase": ["DeafLight", "GagLight", "Freeze"],
  "ItemDevices/DollBox": ["Freeze"],
  "ItemDevices/FuckMachine": ["Mounted", "Freeze"],
  "ItemDevices/FurBlanketWrap": ["Block", "Freeze"],
  "ItemDevices/FuturisticCrate": ["Tethered"],
  "ItemDevices/GiftBox": ["Tethered"],
  "ItemDevices/GlueFloor": ["Freeze"],
  "ItemDevices/Highchair": ["Freeze"],
  "ItemDevices/InflatableBodyBag": ["Block", "Freeze"],
  "ItemDevices/InflatableRestraintBag": ["Freeze", "Block", "Mounted"],
  "ItemDevices/KabeshiriWall": ["Block", "Tethered", "Freeze"],
  "ItemDevices/Kennel": ["Tethered"],
  "ItemDevices/LeatherCage": ["Freeze"],
  "ItemDevices/Locker": ["Freeze"],
  "ItemDevices/LowCage": ["Freeze"],
  "ItemDevices/MedicalBed": ["Freeze", "Mounted"],
  "ItemDevices/MilkCan": ["BlindHeavy", "GagHeavy", "Freeze"],
  "ItemDevices/Net": ["Freeze", "Block"],
  "ItemDevices/OneBarGirl": ["Freeze", "Mounted"],
  "ItemDevices/OneBarPrison": ["Freeze", "Mounted"],
  "ItemDevices/PersonalCage": ["Freeze"],
  "ItemDevices/PetBed": ["Tethered"],
  "ItemDevices/Pole": ["Mounted"],
  "ItemDevices/SaddleStand": ["Freeze", "Mounted"],
  "ItemDevices/SmallDisplayCase": ["DeafLight", "GagLight", "Freeze"],
  "ItemDevices/SmallLocker": ["Freeze"],
  "ItemDevices/SmallWoodenBox": ["BlindNormal", "GagLight", "Freeze"],
  "ItemDevices/SmallWoodenBoxOpenHead": ["Freeze", "Block"],
  "ItemDevices/Snowman": ["Freeze", "Block"],
  "ItemDevices/Stroller": ["Freeze"],
  "ItemDevices/Sybian": ["Freeze", "Mounted"],
  "ItemDevices/TheDisplayFrame": ["Freeze", "Block", "Mounted"],
  "ItemDevices/TheHangingFrame": ["Freeze", "Block", "Mounted"],
  "ItemDevices/Throne": ["Mounted"],
  "ItemDevices/TransportWoodenBox": ["Freeze"],
  "ItemDevices/Trolley": ["Freeze", "Mounted"],
  "ItemDevices/Vacbed": ["Freeze", "Block", "Mounted"],
  "ItemDevices/VacbedClear": ["Freeze", "Block", "Mounted"],
  "ItemDevices/VacBedDeluxe": ["Freeze", "Block", "Mounted"],
  "ItemDevices/VacCube": ["Freeze", "Block"],
  "ItemDevices/WaterCell": ["GagMedium", "Freeze"],
  "ItemDevices/WoodenBox": ["Freeze"],
  "ItemDevices/WoodenBoxOpenHead": ["Freeze", "Block"],
  "ItemDevices/WoodenHorse": ["Freeze", "Mounted"],
  "ItemDevices/WoodenRack": ["Freeze", "Mounted"],
  "ItemDevices/WoodenStocks": ["Freeze", "Block", "Mounted"],
  "ItemEars/HeavyDutyEarPlugs": ["DeafHeavy"],
  "ItemEars/LightDutyEarPlugs": ["DeafLight"],
  "ItemFeet/FloorShackles": ["Freeze"],
  "ItemFeet/Slime": ["Freeze"],
  "ItemFeet/SpreaderDildoBar": ["Freeze"],
  "ItemFeet/SpreaderVibratingDildoBar": ["Freeze"],
  "ItemFeet/SuspensionCuffs": ["Block", "Freeze"],
  "ItemFeet/WoodenCuffs": ["Freeze"],
  "ItemHands/BalletBootsMittens": ["Block"],
  "ItemHands/CheerleaderPomPoms": ["Block"],
  "ItemHands/DuctTape": ["Block"],
  "ItemHands/ElbowLengthMittens": ["Block"],
  "ItemHands/FoamMittens": ["Block"],
  "ItemHands/GlueMittens": ["Block"],
  "ItemHands/HoofMittens": ["Block"],
  "ItemHands/LatexBondageMitts": ["Block"],
  "ItemHands/LeatherMittens": ["Block"],
  "ItemHands/PaddedLeatherMittens": ["Block"],
  "ItemHands/PaddedMittens": ["Block"],
  "ItemHands/PawMittens": ["Block"],
  "ItemHands/PolishedMittens": ["Block"],
  "ItemHands/PonyMittensBinder": ["Block"],
  "ItemHands/SmoothLeatherMittens1": ["Block"],
  "ItemHead/AnimeLenses": ["BlindLight"],
  "ItemHead/BlackoutLenses": ["BlindHeavy"],
  "ItemHead/ClothBlindfold": ["BlindLight"],
  "ItemHead/FrilledSleepMask": ["BlindLight"],
  "ItemHead/FullBlindfold": ["BlindHeavy"],
  "ItemHead/FurScarf": ["BlindLight"],
  "ItemHead/KittyBlindfold": ["BlindLight"],
  "ItemHead/LatexBlindfold": ["BlindNormal"],
  "ItemHead/LeatherBlindfold": ["BlindNormal"],
  "ItemHead/LeatherSlimMask": ["BlindHeavy", "GagLight"],
  "ItemHead/LeatherSlimMaskOpenEyes": ["GagLight"],
  "ItemHead/LeatherSlimMaskOpenMouth": ["BlindHeavy"],
  "ItemHead/LewdBlindfold": ["BlindLight"],
  "ItemHead/PaddedBlindfold": ["BlindHeavy"],
  "ItemHead/Pantyhose": ["BlindLight"],
  "ItemHead/PrisonLockdownBlindfold": ["BlindNormal"],
  "ItemHead/RopeBlindfold": ["BlindLight"],
  "ItemHead/ScarfBlindfold": ["BlindLight"],
  "ItemHead/SleepMask": ["BlindLight"],
  "ItemHead/Slime": ["BlindLight"],
  "ItemHead/SmallBlindfold": ["BlindLight"],
  "ItemHead/StuddedBlindfold": ["BlindNormal"],
  "ItemHead/Tentacles": ["BlindNormal"],
  "ItemHood/BlanketHood": ["BlindNormal", "GagLight"],
  "ItemHood/CanvasHood": ["BlindHeavy", "GagHeavy", "DeafLight"],
  "ItemHood/CorsetHood": ["GagVeryHeavy"],
  "ItemHood/CustomBallHood": ["BlindHeavy", "DeafLight"],
  "ItemHood/DogHood": ["GagNormal"],
  "ItemHood/FoxHood": ["GagHeavy"],
  "ItemHood/FoxyMask": ["GagLight"],
  "ItemHood/HeadboxSeethrough": ["BlindHeavy"],
  "ItemHood/InflatedBallHood": ["BlindHeavy", "DeafLight"],
  "ItemHood/LampHeadHood": ["BlindLight"],
  "ItemHood/LatexBunny": ["GagHeavy", "DeafLight"],
  "ItemHood/LeatherHood": ["BlindHeavy", "DeafLight", "GagNormal"],
  "ItemHood/LeatherHoodOpenEyes": ["GagLight"],
  "ItemHood/LeatherHoodOpenMouth": ["BlindHeavy"],
  "ItemHood/LeatherHoodSealed": ["BlindHeavy", "GagLight"],
  "ItemHood/LeatherHoodSensDep": ["BlindHeavy", "DeafHeavy", "GagHeavy"],
  "ItemHood/PantyHood": ["BlindLight"],
  "ItemHood/Pantyhose": ["BlindLight"],
  "ItemHood/PolishedSteelHood": ["BlindHeavy", "DeafLight", "GagHeavy"],
  "ItemHood/PonyHood": ["BlindLight", "GagNormal"],
  "ItemHood/SackHood": ["BlindHeavy"],
  "ItemHood/SensoryDeprivationHood": ["DeafTotal", "BlindHeavy", "GagVeryHeavy"],
  "ItemHood/Slime": ["BlindLight", "DeafHeavy", "GagHeavy"],
  "ItemHood/TransparentLatexHood": ["BlindLight"],
  "ItemLegs/MermaidTail": ["Freeze"],
  "ItemMouth/AOMGag": ["GagNormal"],
  "ItemMouth/Ball": ["GagMedium"],
  "ItemMouth/BallGag": ["GagMedium"],
  "ItemMouth/BallGagMask": ["GagMedium"],
  "ItemMouth/BambooGag": ["GagNormal"],
  "ItemMouth/BigMouth": ["GagLight"],
  "ItemMouth/BishopGag": ["GagHeavy"],
  "ItemMouth/BitGag": ["GagNormal"],
  "ItemMouth/BoneGag": ["GagLight"],
  "ItemMouth/CaneGag": ["GagLight"],
  "ItemMouth/CarrotGag": ["GagMedium"],
  "ItemMouth/ChloroformCloth": ["GagVeryLight"],
  "ItemMouth/ChopstickGag": ["GagNormal"],
  "ItemMouth/ClothStuffing": ["GagLight"],
  "ItemMouth/CropGag": ["GagLight"],
  "ItemMouth/CupholderGag": ["GagEasy"],
  "ItemMouth/DeepthroatGag": ["GagHeavy"],
  "ItemMouth/DildoGag": ["GagMedium"],
  "ItemMouth/DogMuzzleExposed": ["GagNormal"],
  "ItemMouth/DusterGag": ["GagEasy"],
  "ItemMouth/FoxyHarnessPanelGag": ["GagEasy"],
  "ItemMouth/FunnelGag": ["GagMedium"],
  "ItemMouth/FurScarf": ["GagLight"],
  "ItemMouth/GlueGag": ["GagHeavy"],
  "ItemMouth/HarnessBallGag": ["GagMedium"],
  "ItemMouth/HarnessBallGag1": ["GagHeavy"],
  "ItemMouth/HarnessPacifierGag": ["GagLight"],
  "ItemMouth/HarnessPanelGag": ["GagEasy"],
  "ItemMouth/HookGagMask": ["GagEasy"],
  "ItemMouth/HorrorMuzzle": ["GagHeavy"],
  "ItemMouth/KittyHarnessPanelGag": ["GagEasy"],
  "ItemMouth/LatexBallMuzzleGag": ["GagMedium"],
  "ItemMouth/LatexPostureCollar": ["GagNormal"],
  "ItemMouth/LewdGag": ["GagLight"],
  "ItemMouth/LipGag": ["GagLight"],
  "ItemMouth/MilkBottle": ["GagVeryLight"],
  "ItemMouth/MouthFeatureGag": ["GagVeryLight"],
  "ItemMouth/PacifierGag": ["GagVeryLight"],
  "ItemMouth/PaciGag": ["GagLight"],
  "ItemMouth/PantiesMask": ["GagVeryLight"],
  "ItemMouth/PantyStuffing": ["GagLight"],
  "ItemMouth/PlasticWrap": ["GagLight"],
  "ItemMouth/PumpkinGag": ["GagEasy"],
  "ItemMouth/PumpkinHarnessGag": ["GagMedium"],
  "ItemMouth/QualityHarnessGag": ["GagMedium"],
  "ItemMouth/RingGag": ["GagEasy"],
  "ItemMouth/RopeGag": ["GagLight"],
  "ItemMouth/RoseBallGag": ["GagMedium"],
  "ItemMouth/ShoeGag": ["GagMedium"],
  "ItemMouth/Slime": ["GagMedium"],
  "ItemMouth/SockStuffing": ["GagLight"],
  "ItemMouth/SpiderGag": ["GagEasy"],
  "ItemMouth/StitchedMuzzleGag": ["GagEasy"],
  "ItemMouth/Stitches": ["GagHeavy"],
  "ItemMouth/Tentacles": ["GagMedium"],
  "ItemMouth/TonguePiercingGag": ["GagNormal"],
  "ItemMouth/TongueStrapGag": ["GagEasy"],
  "ItemMouth/WebGag": ["GagEasy"],
  "ItemMouth/WiffleGag": ["GagNormal"],
  "ItemMouth/XLBoneGag": ["GagNormal"],
  "ItemMouth/XmasStickerGag": ["GagEasy"],
  "ItemMouth2/BallGag": ["GagMedium"],
  "ItemMouth2/BallGagMask": ["GagMedium"],
  "ItemMouth2/BoneGag": ["GagLight"],
  "ItemMouth2/CarrotGag": ["GagMedium"],
  "ItemMouth2/ChloroformCloth": ["GagVeryLight"],
  "ItemMouth2/CupholderGag": ["GagEasy"],
  "ItemMouth2/DildoGag": ["GagMedium"],
  "ItemMouth2/DusterGag": ["GagEasy"],
  "ItemMouth2/FoxyHarnessPanelGag": ["GagEasy"],
  "ItemMouth2/FurScarf": ["GagLight"],
  "ItemMouth2/HarnessBallGag": ["GagMedium"],
  "ItemMouth2/HarnessBallGag1": ["GagHeavy"],
  "ItemMouth2/HarnessPanelGag": ["GagEasy"],
  "ItemMouth2/KittyHarnessPanelGag": ["GagEasy"],
  "ItemMouth2/LatexBallMuzzleGag": ["GagMedium"],
  "ItemMouth2/LatexPostureCollar": ["GagNormal"],
  "ItemMouth2/LewdGag": ["GagLight"],
  "ItemMouth2/LipGag": ["GagLight"],
  "ItemMouth2/PaciGag": ["GagLight"],
  "ItemMouth2/PantiesMask": ["GagVeryLight"],
  "ItemMouth2/PlasticWrap": ["GagLight"],
  "ItemMouth2/PumpkinGag": ["GagEasy"],
  "ItemMouth2/RingGag": ["GagEasy"],
  "ItemMouth2/RopeGag": ["GagLight"],
  "ItemMouth2/ShoeGag": ["GagMedium"],
  "ItemMouth2/Slime": ["GagMedium"],
  "ItemMouth2/SpiderGag": ["GagEasy"],
  "ItemMouth2/StitchedMuzzleGag": ["GagEasy"],
  "ItemMouth2/Tentacles": ["GagMedium"],
  "ItemMouth2/WebGag": ["GagLight"],
  "ItemMouth2/WiffleGag": ["GagNormal"],
  "ItemMouth3/BallGag": ["GagMedium"],
  "ItemMouth3/BallGagMask": ["GagMedium"],
  "ItemMouth3/BoneGag": ["GagLight"],
  "ItemMouth3/CarrotGag": ["GagMedium"],
  "ItemMouth3/ChloroformCloth": ["GagVeryLight"],
  "ItemMouth3/CupholderGag": ["GagEasy"],
  "ItemMouth3/DildoGag": ["GagMedium"],
  "ItemMouth3/DusterGag": ["GagEasy"],
  "ItemMouth3/FoxyHarnessPanelGag": ["GagEasy"],
  "ItemMouth3/FurScarf": ["GagLight"],
  "ItemMouth3/HarnessBallGag": ["GagMedium"],
  "ItemMouth3/HarnessBallGag1": ["GagHeavy"],
  "ItemMouth3/HarnessPacifierGag": ["GagLight"],
  "ItemMouth3/HarnessPanelGag": ["GagEasy"],
  "ItemMouth3/HorrorMuzzle": ["GagHeavy"],
  "ItemMouth3/KittyHarnessPanelGag": ["GagEasy"],
  "ItemMouth3/LatexBallMuzzleGag": ["GagMedium"],
  "ItemMouth3/LatexPostureCollar": ["GagNormal"],
  "ItemMouth3/LewdGag": ["GagLight"],
  "ItemMouth3/LipGag": ["GagLight"],
  "ItemMouth3/PantiesMask": ["GagVeryLight"],
  "ItemMouth3/PlasticWrap": ["GagLight"],
  "ItemMouth3/PumpkinGag": ["GagEasy"],
  "ItemMouth3/RingGag": ["GagEasy"],
  "ItemMouth3/RopeGag": ["GagLight"],
  "ItemMouth3/ShoeGag": ["GagMedium"],
  "ItemMouth3/Slime": ["GagMedium"],
  "ItemMouth3/SpiderGag": ["GagEasy"],
  "ItemMouth3/StitchedMuzzleGag": ["GagEasy"],
  "ItemMouth3/Tentacles": ["GagMedium"],
  "ItemMouth3/WebGag": ["GagLight"],
  "ItemMouth3/WiffleGag": ["GagNormal"],
  "ItemMouth3/XmasStickerGag": ["GagEasy"],
  "ItemNeck/ComboHarness": ["GagMedium", "BlindNormal"],
  "ItemNeck/LatexPostureCollar": ["GagNormal"],
  "ItemNeck/LeatherCorsetCollar": ["GagNormal"],
  "ItemNeckRestraints/CollarLeash": ["Leash"],
  "ItemNeckRestraints/ChainLeash": ["Leash"],
  "ItemNeckRestraints/CollarChainLong": ["Tethered"],
  "ItemNeckRestraints/CollarChainMedium": ["Tethered"],
  "ItemNeckRestraints/CollarChainShort": ["Freeze"],
  "ItemNeckRestraints/CollarRopeLong": ["Tethered"],
  "ItemNeckRestraints/CollarRopeMedium": ["Tethered"],
  "ItemNeckRestraints/CollarRopeShort": ["Freeze"],
  "ItemNeckRestraints/PetPost": ["Tethered"],
  "ItemNeckRestraints/Post": ["Freeze"],
  "ItemTorso/FullBodyStraps": ["Block"],
};
